apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - frontend-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend.default.svc.cluster.local
            port:
              number: 80
---

apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: frontend-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway  # matches the labels on the istio-ingress Service
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
