apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simplewebsite
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KeerthanaGoka/aws-eks
    targetRevision: main
    path: manifests/microservices-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
